### ISSUE TITLE
Design extract & load via YAML or JSON

### ISSUE THREAD

**Issue by lkhusid** [oneops/display#39]
Implement "bulk" design update (import) and export based on simple configuration described in YAML format.   This will allow users to maintain design "as a whole" in external repositories and update (sync/import) design in one command.   This will also proliferate the design sharing between different organizations/entities.   Two new routes:

GET .../ORG_NAME/assemblies/<ASSEMBLY>/design[.yaml | .json | ]

PUT .../ORG_NAME/assemblies/<ASSEMBLY>/design

**Comment by kfilipovski** [comment]
@lkhusid @vitaliyzinchenko I used this feature yesterday.  It works great when you start out with a simple use-case, but as soon as you start using it for something more _real_ my impression is that the format becomes too verbose.  For example, the export of the oneops app design was 1604 lines and that's _without_ the attributes.  Even if I breakout each platform it still becomes hard to manage it.  I think we need to consolidate some more.

For example a platform envelope looks like this now:
~~~
  -
    name: "postgres"
    type: "catalog.Platform"
    attributes:
      major_version: "1"
      description: "PostgresQL DB"
      source: "main"
      version: "1"
      pack: "postgresql"
~~~

... and I think it can be consolidated to something like this so it goes from 9 lines to 2
~~~
postgres:
    circuit: oneops/postgresql:1
~~~

also components can be consolidated from this:
~~~
      -
        name: "secgroup"
        type: "catalog.oneops.1.Secgroup"
        comments: ""
        template: "secgroup"
~~~

... to this:
~~~
secgroup:
  template: "secgroup:oneops.1.Secgroup"
~~~

Also, I think one pretty obvious feature to add is a pack pull/export to setup an initial yaml for users.  This would be a huge timesaver since you would not need to start from a blank file and you would not need to go to the UI to create a design there, then pull/export.  The pack developer can designate which components/attributes should be exported by default (i.e what they are recommending the app designer should set).  We can also use this info in the UI too.

**Comment by kfilipovski** [comment]
@lkhusid please rename the URL routes to use dedicated REST verbs:

~~~
GET /ORG_NAME/assemblies//design/pull[ .yaml | .json ]
GET /ORG_NAME/assemblies//design/push (edit for the UI tab)
PUT /ORG_NAME/assemblies//design/push
~~~

**Comment by lkhusid** [comment]
After numerous discussions we decide to go with "**extract**" & "**load**" terminology.   So the API endpoints are:

GET /ORG/assemblies/ASSEMBLY/design/extract[ .yaml | .json ]
GET /ORG/assemblies/ASSEMBLY/design/load   -- (edit page for UI only)
PUT /ORG/assemblies/ASSEMBLY/design/load (use "data_fie" body parameter for uploading a file [via multipart form submission] or "data" parameter for directly specifying YAML or JSON string for design configuration).
